# Generated by Django 5.0.4 on 2024-04-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_message_date_remove_message_receiver_and_more'),
        ('main_app', '0005_alter_profile_avatar'),
    ]

    operations = [
    ]
