# Generated by Django 5.0.4 on 2024-04-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
