# Generated by Django 5.0.4 on 2024-04-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20240424_1312'),
        ('main_app', '0006_merge_20240424_1321'),
        ('main_app', '0009_remove_blog_image'),
    ]

    operations = [
    ]
